f = open("eco_project.txt",'w')
print("File Name: ",f.name)
print("File Mode: ",f.mode)
print("Is File Readable: ",f.readable())
print("Is File Writable: ",f.writable())
print("Is File closed: ",f.close)
f.close()
print("Is File closed: ",f.closed)
